version: "3.8"

# FastAPI
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: # bind mount settings
      - type: bind
        source: ./src
        target: /src
    expose:
      - 8000
    ports:
      - 8000:8000
    restart: always
    # environment:
    #   DB_HOST: ${DB_HOST}
    #   DB_PORT: ${DB_PORT}
    #   DB_NAME: ${DB_NAME}
    #   DB_USER: ${DB_USER}
    #   DB_PASSWORD: ${DB_PASSWORD}
    # depends_on:
    #   - db

  # PostreSQL
#   db:
#     image: postgres:13-alpine
#     volumes:
#       - postgres:/var/lib/postgresql/data
#     expose:
#       - 5432
#     restart: always
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}

# volumes:
#   postgres:
